# CS231n Python Numpy Tutorial

In [3]:
import sys
import numpy as np

print(sys.version)

2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]


# Python

In [22]:
def quicksort(arr):
    if len(arr) <=1:
        return arr
    print arr
    pivot = arr[len(arr) /2]
    middle = [x for x in arr if x == pivot]
    left = [x for x in arr if x < pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print quicksort([3,6,8,10,1,2,1])

[3, 6, 8, 10, 1, 2, 1]
[3, 6, 8, 1, 2, 1]
[3, 6, 8, 2]
[3, 6, 2]
[3, 2]
[1, 1, 2, 3, 6, 8, 10]


In [27]:
hw12 = '%s %s %d' % ('HELLO', 'WORLD', 12)
print hw12

HELLO WORLD 12


In [31]:
print hw12.capitalize()
print hw12.upper()
print hw12.rjust(20)
print hw12.center(20)
print hw12.replace('L', 'l')

Hello world 12
HELLO WORLD 12
      HELLO WORLD 12
   HELLO WORLD 12   
HEllO WORlD 12


## Lists

In [32]:
xs = [3,1,2]
print xs, xs[2]
print xs[-1] #negative count from the end of the list
xs[2] = 'foo'
print xs
xs.append('bar')
print xs
x = xs.pop()
print x, xs

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


### slicing

In [37]:
nums = range(5)
print nums
print nums [2:4]
print nums [2:]
print nums [:2]
print nums[:]
print nums[:-1]
nums[2:4] =[8,9]
print nums

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


### looping

In [40]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
           print animal

cat
dog
monkey


In [42]:
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx, animal)

#0: cat
#1: dog
#2: monkey


### comprehensions

In [49]:
nums = range(5)

squares = []
for x in nums:
    squares.append(x **2)
print squares

squares = []
squares = [x ** 2 for x in nums]
print squares

even_squares = [x ** 2 for x in nums if x % 2 ==0]
print even_squares

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]
[0, 4, 16]


## Dictionaries

In [50]:
d = {'cat': 'cute', 'dog': 'furry'}
print d['cat']
print 'cat' in d
print 'fish' in d
d['fish'] = 'wet'
print d.get('monkey', 'n/a')
print d.get('fish', 'n/a')
del d['fish']
d.get('fish', 'n/a')

cute
True
False
n/a
wet


'n/a'

### loops

In [51]:
d = {'person':2, 'cat':4, 'spider':8}
for animal in d:
    legs = d[animal]
    print 'A %s has %d legs' % (animal, legs)

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


In [52]:
for animal, legs in d.iteritems():
        print 'A %s has %d legs' % (animal, legs)

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


### comprehensions

In [53]:
nums = [0,1,2,3,4]
even_num_to_square = {x : x **2 for x in nums if x %2 == 0}
print even_num_to_square

{0: 0, 2: 4, 4: 16}


## Sets

In [60]:
animals = {'cat', 'dog'}
print 'cat' in animals   # Check if an element is in a set; prints "True"
print 'fish' in animals  # prints "False"
animals.add('fish')      # Add an element to a set
print 'fish' in animals  # Prints "True"
print len(animals)       # Number of elements in a set; prints "3"
animals.add('cat')       # Adding an element that is already in the set does nothing
print len(animals)       # Prints "3"
animals.remove('cat')    # Remove an element from a set
print len(animals)       # Prints "2"

numbers = {x for x in range(10) if x % 2 == 0} ##unordered sets
print numbers

True
False
True
3
3
2
set([0, 8, 2, 4, 6])


## Tuples
A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot

In [56]:
d = {(x, x+1): x for x in range(10)} #dic with tuple keys
print d
t = (5,6) # tuple
print t
print type(t)
print d[t]
print d[(1,2)]


{(0, 1): 0, (1, 2): 1, (6, 7): 6, (5, 6): 5, (7, 8): 7, (8, 9): 8, (4, 5): 4, (2, 3): 2, (9, 10): 9, (3, 4): 3}
(5, 6)
<type 'tuple'>
5
1


## Functions

In [61]:
def hello(name, loud=False):
    if loud:
        print 'HELLO %s' % name.upper()
    else:
        print 'Hello %s ' % name
hello('Bob')
hello('Fred', loud=True)


Hello Bob 
HELLO FRED


## Classes

In [66]:
class Greeter(object):
    #constructor
    def __init__(self, name):
        self.name = name
    
    def greet(self, loud=False):
        if loud:
            print 'HELLO %s!' % self.name.upper()
        else:
            print 'Hello %s' % self.name

g = Greeter('Fred')
g.greet()
g.greet(loud=True)

g2 = Greeter('')
g2.greet()


Hello Fred
HELLO FRED!
Hello 


# Numpy
http://scipy.github.io/old-wiki/pages/NumPy_for_Matlab_Users


## Arrays

In [8]:
a = np.array([1,2,3]) #rank 1 array
print type(a)
print a.shape
print a[0], a[1], a[2]
a[0] = 5
print a

b = np.array([[1,2,3], [4,5,6]]) #rank 2 array
print b.shape
print b[0,0], b[0,1], b[1,0]

c = np.array([[1,2,3,4,5,6]])
print c
print c.shape
print c.size

<type 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4
[[1 2 3 4 5 6]]
(1, 6)
6


In [74]:
a = np.zeros((2,2))
print a

b = np.ones((1,2))
print b

c = np.full((2,2), 7)
print c

d = np.eye(2)
print d

e = np.random.random((2,2))
print e

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 7.  7.]
 [ 7.  7.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.28307453  0.86310665]
 [ 0.58601707  0.58661934]]


## Array Indexing

### slicing

In [78]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

b = a[:2, 1:3]
print b

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print a[0, 1]
b[0,0] = 77 ## same piece of data as a[0,0]
print a[0,1] ## <!-- look at this reference


[[2 3]
 [6 7]]
2
77


In [11]:
# You can also mix integer indexing with slice indexing. 
# However, doing so will yield an array of lower rank than the original array.

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :] #rank 1 view of second row of a
row_r2 = a[1:2, :] #rank2 (same rank as original) view of seond row of a

print row_r1, row_r1.shape
print row_r2, row_r2.shape
print
# we can make distinction when accessing columns
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print col_r1, col_r1.shape
print col_r2, col_r2.shape


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)

[[  1 100   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


### integer array indexing
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.

In [18]:
a = np.array([[1,2], [3, 4], [5, 6]])

print a[[0, 1, 2], [0, 1, 0]] 

print np.array([a[0, 0], a[1, 1], a[2, 0]]) 
print

# When using integer array indexing, you can reuse the same
# element from the source array:
print a[[0, 0], [1, 1]]


[1 4 5]
[1 4 5]

[2 2]


# Indexing Numpy Arrays

In [32]:
a = np.arange(10)
b = np.reshape(np.arange(9), (3,3))
c = np.reshape(np.arange(2*3*4), (2,3,4))
print a
print b
print
print c
print


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



## Elements


In [31]:
#simple way to pick out elements
print a[1]
print b[1,1]
print c[1,1,1]
print
print c[1,0,1]
#is the same as...
print c[(1,0,1)]
# ...This peculiar-looking syntax is constructing a tuple, python's data structure for immutable sequences,
# and using that tuple as an index into the array.
i = (1,0,1)
print c[i]
print

for i in np.ndindex(b.shape):
    print i, b[i]
print

# when you select an element from an array, what you get back has the same type as the array elements. 
# This may sound obvious, and in a way it is, but keep in mind that even innocuous numpy arrays like our A, B, and C 
# often contain types that are not quite the python types
x = 12
print type(x)
xnp = a[1]
print type(xnp)
print


1
4
17

13
13
13

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

<type 'int'>
<type 'numpy.int64'>



## Slices

In [33]:
print 2*a

[ 0  2  4  6  8 10 12 14 16 18]


In [34]:
print a[1:]
print a[:-1]
print a[1:] - a[:-1]

[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]
[1 1 1 1 1 1 1 1 1]


In [39]:
#step
print a[::2]
print a[1::2]
print a[::-1]

[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


In [38]:
#If you specify a slice that happens to have only one element, you get an array in return that happens to have only one element
print a[5:6]
print a[5]

[5]
5


In [43]:
#Just as one can retrieve elements of an array as a subarray rather than one-by-one, 
# one can modify them as a subarray rather than one-by-one:
t = a.copy()
print t
print t[1::2]
t[1::2] = -np.arange(5)
print t[1::2]
print t

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[ 0 -1 -2 -3 -4]
[ 0  0  2 -1  4 -2  6 -3  8 -4]
[ 0 -1 -2 -3 -4]


In [45]:
t = a.copy()
t[:4] = np.array([[0,1], [1,0])

SyntaxError: invalid syntax (<ipython-input-45-07745912e369>, line 3)

In [49]:
t = a.copy()
print t
t[:4] = np.array([[0,1], [1,0]]).ravel()
print t

[0 1 2 3 4 5 6 7 8 9]
[0 1 1 0 4 5 6 7 8 9]


In [50]:
a[1::2]
print a
s = slice(1, None, 2)
print a[s]
print b[s]


[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[[3 4 5]]


## Multidimensional slices

In [53]:
print b
print
print b[:2, :]
print
print b[:, ::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]
 [3 4 5]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [56]:
# when one supplies a number for (say) the first axis, 
# the result is no longer a two-dimensional array; it's now a one-dimensional array.
print b[:,:]
print
print b[0,:]
print 
print b[0,0]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2]

0


In [59]:
# If you are used to working with matrices, you may want to preserve a distinction between "row vectors" 
# and "column vectors". numpy supports only one kind of one-dimensional array, but you could represent row and 
# column vectors as two-dimensional arrays, one of whose dimensions happens to be one. 
# Unfortunately indexing of these objects then becomes cumbersome.
print b
print
print b[:, 0:1] # 3 x 1 vector
print
print b[:,0] #range 1 array

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0]
 [3]
 [6]]

[0 3 6]


## Fancy Indexing
Slices are very handy, and the fact that they can be created as views makes them efficient. But some operations cannot really be done with slices; for example, suppose one wanted to square all the negative values in an array. Short of writing a loop in python, one wants to be able to locate the negative values, extract them, square them, and put the new values where the old ones were

In [61]:
print a
t = a.copy() - 5
print t
t[t<0] **= 2
print t


[0 1 2 3 4 5 6 7 8 9]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[25 16  9  4  1  0  1  2  3  4]
[False False False  True  True  True  True  True  True  True]


In [63]:
print a
print a<5
print (a>2) & (a<6)

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[False False False  True  True  True False False False False]


In [64]:
t = a.copy()
print t
d = (a>2) & (a<6)
t[d] = -7
print t

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2 -7 -7 -7  6  7  8  9]


## List of locations indexing
It happens with some frequency that one wants to pull out values at a particular location in an array. If one wants a single location, one can just use simple indexing. But if there are many locations, you need something a bit more clever. Fortunately numpy supports a mode of fancy indexing that accomplishes this

In [65]:
primes = np.array([2,3,5,7,11,13,17,19,23])
idx = [3,4,1,2,2]
print primes[idx]

[ 7 11  3  5  5]


In [68]:
# When you index with an array that is not an array of booleans, or with a list,
# numpy views it as an array of indices. The array can be any shape, and the returned array has the same shape:
primes = np.array([2,3,5,7,11,13,17,19,23])
print b
primes[b[2:4]]
# effectivly uses the original array (b) as a lookup table


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[17, 19, 23]])